#端口配置
server:
  port: 9203

spring:
  #mysql
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/siam_cloud?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: root

#  #mongodb(默认时没有账号密码的)
#  #  application:
#  #    name: spring-boot-mongodb
#  data:
#    mongodb:
#      host: 127.0.0.1
#      port: 27017
#      database: siam_cloud
#
#    #elasticsearch
#    elasticsearch:
#      cluster-name: es-cluster
#      cluster-nodes: 127.0.0.1:9300

  #thymeleaf
  thymeleaf:
    mode: LEGACYHTML5
    encoding: utf-8
    servlet:
      content-type: text/html
    #开发时关闭缓存,不然没法看到实时页面
    cache: false

  #redis单例模式
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    jedis:
      pool:
        # 连接池中的最大空闲连接个数
        max-idle: 8
        # 连接池中的最小空闲连接个数
        min-idle: 0
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
    # 连接超时时间（毫秒）
    timeout: 600000ms

#  #rabbitmq
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: root
#    password: rabbitmq123
#    # 消息发送到交换机确认机制,是否确认回调
#    publisher-confirms: true
#    # 消息发送到交换机确认机制,是否返回回馈
#    publisher-returns: true

  #允许bean重复定义/允许bean覆盖
  main:
    allow-bean-definition-overriding: true

  jackson:
    #时间戳统一转换为指定格式
    date-format: yyyy/MM/dd HH:mm:ss
    #时区修改为东8区
    time-zone: GMT+8

  #服务别名，注册到注册中心上的名字
  application:
    name: goods-siam

  #配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  #邮件相关配置
  mail:
    host: smtp.126.com
    password: siam1026@163.com
    username: siam1026@163.com
    properties:
      mail:
        smtp:
          #非必要参数
          auth: true
          port: 465
          ssl.enable: true
          starttls.enable: true
          #必要参数
          timeout: 25000
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          socketFactory.port: 465

#阿里云配置
aliyun:
  #短信服务
  dysms:
    accessKeyId: siam1026@163.com
    secret: siam1026@163.com
    signName: 暹罗外卖
    templateCode: SMS_164681243
    templateCode_verificationCode: SMS_177547102
    templateCode_fatalError: SMS_187746991
    templateCode_pickUpOrderComplete: SMS_193245384
    templateCode_takeOutOrderDelivery: SMS_193235459
    templateCode_couponsDistributeReminder: SMS_189032218
    templateCode_couponsOverdueReminder: SMS_190270439

  #OSS存储
  oss:
    accessKeyId: siam1026@163.com
    secret: siam1026@163.com
    endpoint: http://oss-cn-hangzhou.aliyuncs.com
    bucketName: siam-hangzhou

  #全国快递物流查询
  express:
    appCode: siam1026@163.com

wxPublicPlatform:
  appId: siam1026@163.com
  secret: siam1026@163.com

#百度地图
baidu:
  map:
    ak: siam1026@163.com

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:com/siam/**/*Mapper.xml
  #  type-aliases-package: com.mht.springbootmybatisplus.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    #配置使用ip地址来注册(默认是主机名称)
    prefer-ip-address: true
    #心跳检测暂时不配置

#feign内部服务调用超时配置
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000

#rocketmq配置
rocketmq:
  #mq开关，关闭则启动时不加载rocketmq
  switch: false
  #消息通道
  name-server: 127.0.0.1:9876
  producer:
    group: goodsProducerGroup

# Seata Config
seata:
  application-id: goods-service
  tx-service-group: my_test_tx_group
  service:
    vgroup-mapping:
      # 此处配置对应Server端配置registry.eureka.application的值
      my_test_tx_group: default
  registry:
    type: eureka
    eureka:
      service-url: http://127.0.0.1:9000/eureka/
      weight: 1

#springboot admin相关配置
management:
  endpoints:
    web:
      exposure:
        include: "*" #'prometheus,health'
        exclude: "shutdown"
      base-path: /actuator
  endpoint:
    health:
      show-details: ALWAYS
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
        step: 1ms
        descriptions: true
    tags:
      # 为指标设置一个Tag，这里设置为应用名，Tag是Prometheus提供的一种能力，从而实现更加灵活的筛选
      application: ${spring.application.name}
  # 禁止Actuator监控以下组件连接
  health:
    rabbit:
      enabled: false
    mongo:
      enabled: false
    elasticsearch:
      enabled: false

#日志配置
logging:
  file:
    name: ./logs/${spring.application.name}/log_info.log
path:
  log: ./logs/${spring.application.name}/
